# Generated by Django 3.2 on 2022-09-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
