# Generated by Django 3.2 on 2022-09-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactus_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='content',
            new_name='message',
        ),
    ]
