# Generated by Django 3.2 on 2022-11-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactus_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ('-date_sent',), 'verbose_name_plural': 'Contact Us'},
        ),
    ]
