# Generated by Django 3.2 on 2022-08-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220821_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
