# Generated by Django 3.2 on 2022-08-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_gender_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('30ml', '30ml'), ('50ml', '50ml'), ('75ml', '75ml'), ('100ml', '100ml')], default='100ml', max_length=12),
        ),
    ]
