# Generated by Django 3.2 on 2022-10-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_review_star_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('30ml', '30ml'), ('50ml', '50ml'), ('75ml', '75ml'), ('100ml', '100ml')], default='100ml', max_length=12),
        ),
    ]
